from django.conf.urls import url, include
from inventory import views as v


urlpatterns = [
    url(r'^$', v.home, name='home'),
    url(r'^download/data/$', v.myview, name='download'),
    url(r'^edit_order/(?P<category>[\w]+)/(?P<id>\d+)/$', v.edit_customer_order, name='edit_order'),
    url(r'^new/order/(?P<category>[\w]+)/(?P<id>\d+)/$', v.new_customer_order, name='new_order'),
    url(r'^lagos/new/order/(?P<category>[\w]+)/(?P<id>\d+)/$', v.lagos_new_customer_order, name='lagos_new_order'),
    url(r'^orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.orders, name='orders'),
    url(r'^(?P<id>\d+)/$', v.order, name='order'),
    url(r'^confirm/(?P<category>[\w]+)/(?P<id>\d+)/$', v.confirm_order, name='confirm_order'),
    url(r'^confirmed/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.confirmed_orders, name='confirmed_orders'),
    url(r'^results/$', v.ajax_user_search, name = 'demo_user_search'),
    url(r'^lagos/orders$', v.lagos_orders, name='lagos_orders'),
    url(r'^ready/lagos/orders$', v.ready_lagos_orders, name='ready_lagos_orders'),
    url(r'^ready/lagos/orders/print/$', v.ready_lagos_orders_print, name='ready_lagos_orders_print'),
    url(r'^non/lagos/orders$', v.non_lagos_orders, name='non_lagos_orders'),
    url(r'^daily/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.daily_orders, name='daily_orders'),
    url(r'^daily/orders/states/$', v.daily_by_state, name='daily_by_state'),
    url(r'^today/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.today_orders, name='today_orders'),
    url(r'^today/orders/coms/(?P<user>[\w]+)/$', v.today_orders_coms, name='today_orders_coms'),
    url(r'^yesterday/orders/coms/(?P<user>[\w]+)/$', v.yesterday_orders_coms, name='yesterday_orders_coms'),
    url(r'^yesterday/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.yesterday_orders, name='yesterday_orders'),
    url(r'^orders/my_orders/$', v.coms_exec_orders, name='coms_exec_orders'),
    url(r'^my/undelivered/orders/(?P<user>[\w]+)/$', v.coms_exec_undelivered_orders, name='coms_exec_undelivered_orders'),
    url(r'^delete_order/(?P<category>[\w]+)/(?P<id>\d+)/$', v.delete_customer_order, name='delete_order'),
    url(r'^order/status/(?P<id>\d+)/$', v.order_status, name='order_status'),
    url(r'^delivered/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.delivered_orders, name='delivered_orders'),
    url(r'^undelivered/orders/(?P<category>[\w]+)/(?P<id>\d+)/$', v.undelivered_orders, name='undelivered_orders'),
    url(r'^new/stock/$', v.new_stock, name='new_stock'),
    url(r'^all/stocks/$', v.all_stocks, name='all_stocks'),
    url(r'^add/stocks/(?P<state>[\w]+)/(?P<id>\d+)/', v.add_stock, name='add_stock'),
    url(r'^daily/total/orders/print/out/$', v.view_pdf, name='daily_total_print_out'),
    url(r'^add/delivery/person/charges/$', v.delivery_person_charges, name='delivery_person_charges'),
    url(r'^all/delivery/person/charges/$', v.all_delivery_person_charges, name='all_delivery_person_charges'),
    url(r'^add/delivery/person/cash/$', v.delivery_person_cash, name='delivery_person_cash'),
    url(r'^all/delivery/person/cash/$', v.all_delivery_person_cash, name='all_delivery_person_cash'),
    url(r'^delete/delivery/person/charges/(?P<id>\d+)/$', v.delete_d_person, name='delete_d_person'),
]