# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('picture_height', models.PositiveIntegerField(blank=True, default=b'200', editable=False, null=True)),
                ('picture_width', models.PositiveIntegerField(blank=True, default=b'200', editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
