# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'SLIMTEA', b'slimtea'), (b'WAISTTRAINER', b'waisttrainer'), (b'MECRAN', b'mecran'), (b'FLATTUMMYTEA', b'flattummytea'), (b'HAIRNOWNOW', b'hairnownow'), (b'MOOLATO', b'moolato'), (b'HAIRNYMPH', b'hairnymph')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ComsReps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('product_quant', models.CharField(default=b'', max_length=300)),
                ('product_value', models.IntegerField(default=b'')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=100)),
                ('state', models.CharField(default=b'', max_length=100)),
                ('coms_exec', models.CharField(default=b'', max_length=50)),
                ('amount_paid', models.IntegerField(default=0)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_person', models.CharField(default=b'', max_length=100)),
                ('order_status', models.CharField(default=b'Not Yet Specified', max_length=50)),
                ('comment', models.TextField(blank=True, default=b'')),
                ('status', models.CharField(default=b'', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'customer orders',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPersonCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_person', models.CharField(default=b'', max_length=100)),
                ('capital', models.IntegerField(blank=True, default=0)),
                ('commission', models.IntegerField(blank=True, default=0)),
                ('incentive', models.IntegerField(blank=True, default=0)),
                ('expenses', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('next_capital', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LagosLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'lagos locations',
            },
        ),
        migrations.CreateModel(
            name='MecranProductTypeLotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MecranProductTypeRemover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MecranProductTypeSerum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MecranProductTypeSoap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'DELIVERED', b'delivered'), (b'UNDELIVERED', b'undelivered'), (b'OTHERS', b'others'), (b'READY', b'ready'), (b'NOT-READY', b'not-ready')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Order Status',
            },
        ),
        migrations.CreateModel(
            name='StateCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'states/countries',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[(b'URGENT', b'urgent'), (b'NOT URGENT', b'not')], default=b'', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slimcoffee', models.IntegerField(default=0)),
                ('slimcoffee_value', models.IntegerField(default=0)),
                ('slimtea', models.IntegerField(default=0)),
                ('slimtea_value', models.IntegerField(default=0)),
                ('flattummy', models.IntegerField(default=0)),
                ('flattummy_value', models.IntegerField(default=0)),
                ('shapeyou', models.IntegerField(default=0)),
                ('shapeyou_value', models.IntegerField(default=0)),
                ('soap', models.IntegerField(default=0)),
                ('soap_value', models.IntegerField(default=0)),
                ('serum', models.IntegerField(default=0)),
                ('serum_value', models.IntegerField(default=0)),
                ('lotion', models.IntegerField(default=0)),
                ('lotion_value', models.IntegerField(default=0)),
                ('spot_removal', models.IntegerField(default=0)),
                ('spot_removal_value', models.IntegerField(default=0)),
                ('molatoo_lotion', models.IntegerField(default=0)),
                ('molatoo_lotion_value', models.IntegerField(default=0)),
                ('molatoo_serum', models.IntegerField(default=0)),
                ('molatoo_serum_value', models.IntegerField(default=0)),
                ('hairnownow', models.IntegerField(default=0)),
                ('hairnownow_value', models.IntegerField(default=0)),
                ('hairnymph', models.IntegerField(default=0)),
                ('hairnymph_value', models.IntegerField(default=0)),
                ('add_stock', models.IntegerField(default=0)),
                ('substract_stock', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('remarks', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slimcoffee_value', models.IntegerField(blank=True, default=0)),
                ('slimtea_value', models.IntegerField(blank=True, default=0)),
                ('flattummy_value', models.IntegerField(blank=True, default=0)),
                ('shapeyou_value', models.IntegerField(blank=True, default=0)),
                ('soap_value', models.IntegerField(blank=True, default=0)),
                ('serum_value', models.IntegerField(blank=True, default=0)),
                ('lotion_value', models.IntegerField(blank=True, default=0)),
                ('spot_removal_value', models.IntegerField(blank=True, default=0)),
                ('total_value', models.IntegerField(blank=True, default=0)),
                ('remarks_value', models.CharField(blank=True, default=b'', max_length=100)),
                ('date_added', models.CharField(blank=True, default=b'', max_length=100)),
                ('stock_added', models.CharField(blank=True, default=b'', max_length=100)),
                ('stock_removed', models.CharField(blank=True, default=b'', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stock Values',
            },
        ),
        migrations.CreateModel(
            name='WaistProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WaistProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MecranCustomerOrders',
            fields=[
                ('customerorders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.CustomerOrders')),
                ('product_type_lotion', models.CharField(blank=True, max_length=50)),
                ('product_type_soap', models.CharField(blank=True, max_length=50)),
                ('product_type_remover', models.CharField(blank=True, max_length=50)),
                ('product_type_serum', models.CharField(blank=True, default=b'', max_length=50)),
            ],
            bases=('inventory.customerorders',),
        ),
        migrations.CreateModel(
            name='WaistTrainerCustomerOrders',
            fields=[
                ('customerorders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.CustomerOrders')),
                ('product_type_waist', models.CharField(blank=True, max_length=50)),
                ('product_size_waist', models.CharField(blank=True, max_length=50)),
            ],
            bases=('inventory.customerorders',),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
