# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='hairnownow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='hairnownow_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='hairnymph',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='hairnymph_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='molatoo_lotion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='molatoo_lotion_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='molatoo_serum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='molatoo_serum_value',
            field=models.IntegerField(default=0),
        ),
    ]
