# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180416_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(default=500, max_length=20),
        ),
    ]
